apiVersion : apps/v1
kind: Deployment
metadata:
  name: dryloayzaculqitestvalidate
spec:
  progressDeadlineSeconds: 3600
  replicas: 1
  template:
    metadata:
      labels:
        app: dryloayzaculqitestvalidate 
    spec:
      containers:
        - name: dryloayzaculqitestvalidate
          image: diegocontainerregistrytest.azurecr.io/dryloayzaculqitestvalidate
          ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: dryloayzaculqitestvalidate