apiVersion : apps/v1
kind: Deployment
metadata:
  name: dryloayzaculqitestvalidate
  labels:
    app: dryloayzaculqitestvalidate
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: dryloayzaculqitestvalidate 
    spec:
      containers:
        - name: dryloayzaculqitestvalidate
          image: diegocontainerregistrytest.azurecr.io/dryloayzaculqitestvalidate
          imagePullPolicy: Always
          ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: dryloayzaculqitestvalidate