apiVersion : apps/v1
kind: Deployment
metadata:
  name: dryloayzaculqitestvalidate
  labels:
    app: dryloayzaculqitestvalidate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dryloayzaculqitestvalidate
  template:
    metadata:
      labels:
        app: dryloayzaculqitestvalidate 
    spec:
      containers:
        - name: dryloayzadeployment
          image: diegocontainerregistrytest.azurecr.io/dryloayzaculqitestvalidate:0.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 8085