apiVersion : apps/v1
kind: Deployment
metadata:
  name: dryloayza-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dryloayzaculqitestvalidate
  template:
    metadata:
      labels:
        app: dryloayzaculqitestvalidate 
    spec:
      containers:
        - name: dryloayza-server
          image: diegocontainerregistrytest.azurecr.io/dryloayzaculqitestvalidate
          imagePullPolicy: "Always"
          ports:
            - name: http-port
              containerPort: 8080