apiVersion: v1
kind: Service
metadata:
    name: dryloayza-service
spec:
    ports:
        - name: http-port
          port: 80
          targetPort: http-port
          protocol: TCP
    selector:
        app: dryloayza-service